export const routes = {
  login: '/login',
  signup: '/signup',
  home: '/',
  staking: '/staking',
  hallsOfFortune: '',
  shop: '/shop',
  inventory: '/inventory',
  gallery: '/gallery',
  openPacks: '/open-packs',
  gloriumShop: 'glorium-shop',
  crafting: '',
  lore: 'https://blog.wolvesofrome.io/lore/',
  marketplace: '',
  roadMap: '/roadmap',
  team: '/team',
  wolfpaper: '/wolfpapers',
  token: '/token',
};

export const routesConfig = [
  {
    title: 'Home',
    url: routes.home,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Inventory',
    url: routes.inventory,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: false,
    isProtected: true,
  },
  {
    title: 'Staking',
    url: routes.staking,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: false,
    isProtected: true,
  },
  {
    title: 'Open Packs',
    url: routes.openPacks,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: false,
    isProtected: true,
  },
  {
    title: 'Gallery',
    url: routes.gallery,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Lore',
    url: routes.lore,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Marketplace',
    url: routes.marketplace,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: true,
    isProtected: true,
  },
  {
    title: 'Crafting',
    url: routes.crafting,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: true,
    isProtected: true,
  },
  {
    title: 'Halls of Fortune',
    url: routes.hallsOfFortune,
    showInMenu: true,
    showInFooter: false,
    isComingSoon: true,
    isProtected: true,
  },
  {
    title: 'Shop',
    url: routes.shop,
    showInMenu: false,
    showInFooter: false,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Roadmap',
    url: routes.roadMap,
    showInMenu: false,
    showInFooter: true,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Wolfpaper',
    url: routes.wolfpaper,
    showInMenu: false,
    showInFooter: true,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Team',
    url: routes.team,
    showInMenu: false,
    showInFooter: true,
    isComingSoon: false,
    isProtected: false,
  },
  {
    title: 'Token',
    url: routes.token,
    showInMenu: false,
    showInFooter: true,
    isComingSoon: false,
    isProtected: false,
  },
];
